services:
  api-1:
    build: ./src
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"
  api-2:
    build: ./src
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"
  lb:
    image: haproxy:3.3-alpine
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"
    depends_on:
      - api-1
      - api-2
