services:
  api-1:
    container_name: api-1
    hostname: api-1
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"
  api-2:
    container_name: api-2
    hostname: api-2
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"
  lb:
    container_name: load-balancer
    image: haproxy:3.3-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"
    depends_on:
      - api-1
      - api-2
